### ISSUE TITLE
Wide header makes Whiteboards disapper

### ISSUE THREAD

**Issue by alxlg** [yoyurec/logseq-awesome-ui#71]
**Info:**
- OS: Linux
- Logseq ver: 0.9.19
- Plugin ver: 2.3.2
- Theme name: Awesome Styler

- [x] ⚠ Do i have issue with DISABLED my `custom.css`?

**Description:**
The setting Header > Wide:
![immagine](https://github.com/yoyurec/logseq-awesome-ui/assets/26327475/afae443b-be5d-433a-ad43-6998d9be0697)
makes Whiteboards disappear.

**To Reproduce:**
1. Enable the setting above
2. Open a Whiteboard

**Expected behavior:**
 1. The Whiteboard should correctly display as always

**Screenshots**
![immagine](https://github.com/yoyurec/logseq-awesome-ui/assets/26327475/9ebb8b34-864c-4fb6-b178-1f855df7357f)

**Comment by yoyurec** [comment]
have you reloaded Logseq?
can't reproduce...

**Comment by alxlg** [comment]
@yoyurec yes, I had this issue for weeks, I can reproduce it with an empty graph, no custom.css and default theme.

The moment I toggle the setting this happens:

Before
![immagine](https://github.com/yoyurec/logseq-awesome-ui/assets/26327475/801a97ca-5e67-4030-b625-f2bb31b7e357)

After
![immagine](https://github.com/yoyurec/logseq-awesome-ui/assets/26327475/5ae47ee8-9b5e-4218-95e1-3353f7bfae3f)

I can live without that setting, I reported this just to let you know.

**Comment by yoyurec** [comment]
>  I had this issue for weeks

interesting, cose week ago I've updated plugin...

**Comment by yoyurec** [comment]
i've updated code...
try latest 2.3.3, should be fixed. hard to fix in "blind mode" ))

**Comment by yoyurec** [comment]
> The moment I toggle the setting this happens

PS: sometimes _(in most plugins **always**, reload needed on every change)_ settings toggling on/off not properly applid "live" - `Ctrl+R` to reload app with new settings and should be ok

**Comment by yoyurec** [comment]
@alxlg ?

**Comment by alxlg** [comment]
Sorry, I have just tried the update and restarted the app. The issue is still there. I understand it may be impossible to solve this without being able to reproduce. Don't worry, I can just use a different setting. In case I have any insight on how to reproduce the issue I will let you know, thank you.

**Comment by 0nxku** [comment]
Maybe it is specific to Linux? I have the same issue and @alxlg's solution have worked for me.

**Comment by falcaopetri** [comment]
I tried Logseq's whiteboard today and found it to be empty, with no toolbar at sight. I was able to track the issue down a little bit more.

I checked that the `Wide` header variant was selected, and that choosing the `Standard` one made the whiteboard work just like reported in this issue. I turned `Wide` on again and started to manually edit the HTML code. Removing the following part of the code made the toolbars to reappear:

https://github.com/yoyurec/logseq-awesome-ui/blob/6d03b0d1b78d9e75dd0413b3e6270025d9f08a8b/src/modules/sidebars/hideRightSidebarToolbar/hiddenRightSidebarToolbar.css#L5-L7

I was also able to make the toolbars to reappear after disabling the `position: relative` of `.cp__sidebar-main-content>div` using the Styles tab:

![image](https://github.com/yoyurec/logseq-awesome-ui/assets/8387736/66b90dea-4651-4e2b-b684-e5591c9378a8)
